### ISSUE TITLE
Set up HTTPS

### ISSUE THREAD

**Issue by agraebe** [yknl/stacks-chain-status#1]
The current JSON endpoint cannot be consumed easily because it is served via `http` / missing SSL certificate. NodeJS will try to verify SSL and block the request

**Comment by agraebe** [comment]
@yknl whenever you get a chance, could you look into that? what would be the effort for this? I could easily get a status checker into the docs PR if this would be done.

**Comment by yknl** [comment]
https://status.test-blockstack.com/ should now work

**Comment by agraebe** [comment]
fantastic, thanks! 👍
